### ISSUE TITLE
You passed "rediss" as protocol instead of the "redis" protocol!

### ISSUE THREAD

**Issue by nheidloff** [ibm-functions/composer#32] opened 2018-01-10 15:43 UTC
Hi, I had Composer running some weeks ago and wanted to use it again today. I had used "fsh app init --auto" and could run my own flows.

Today this command didn't work and gave me an error. So I provisioned a Redis on Compose instance and tried to use it. Since I only saw a "rediss" URL I used it but got this error: 
"You passed "rediss" as protocol instead of the "redis" protocol!"

Since it didn't work I tried "fsh app init --auto" again and the community Redis instance. But I still got the same "rediss" error.

I tried to fix this by deleting the fsh tool and reinstalling it, but even after this I get the same error. Any ideas how to fix this?

**Comment by tardieu** [comment] 2018-01-10 15:45
@starpit ?

**Comment by nheidloff** [comment] 2018-01-10 16:02
Here is the full error:
"node_redis: WARNING: You passed "rediss" as protocol instead of the "redis" protocol!"

which seems to be thrown here: https://github.com/NodeRedis/node_redis/blob/1a4c410b4179d68aee922b80aff583a336251163/lib/createClient.js

I did "npm uninstall -g node_redis" and tried again but no change.

**Comment by starpit** [comment] 2018-01-10 16:29
can you try `fsh app init --reset --url <yourRedisURL>`

**Comment by nheidloff** [comment] 2018-01-11 10:18
Thanks. That worked. I created my own Redis on IBM Cloud via Docker. I haven't closed this issue since I think the --init should still work. Would also be good to update the doc that rediss is not supported (Redis on Compose).

**Comment by starpit** [comment] 2018-01-11 18:15
yup, i agree. i'll open up a separate issue in the shell repo. as this is a shell bug, and close this one (as it is not a bug in the composer library or runtime)

**Closed by starpit** 2018-01-11 18:15 UTC
Labels: shell
