### ISSUE TITLE
fsh webbify doesn't display URL

### ISSUE THREAD

**Issue by cfjedimaster** [ibm-functions/composer#17] opened 2017-10-12 13:45 UTC
In the shell, if you webbify an app, it shows you the URL. In the CLI, it just says: 

    ok: updated action test2

The CLI should also print out the URL to save you an extra step.

**Comment by rabbah** [comment] 2017-10-16 13:14
duplicate of https://github.com/ibm-functions/shell/issues/31.

**Closed by rabbah** 2017-10-16 13:14 UTC
